import { RouteInfo } from '../types.js';

interface PostmanVariable {
  key: string;
  value: string;
  type?: string;
}

interface PostmanQueryParam {
  key: string;
  value: string;
  disabled?: boolean;
}

interface PostmanUrl {
  raw: string;
  host: string[];
  path?: string[];
  query?: PostmanQueryParam[];
  variable?: PostmanVariable[];
}

interface PostmanHeader {
  key: string;
  value: string;
}

interface PostmanRequestItem {
  name: string;
  request: {
    method: string;
    header: PostmanHeader[];
    url: PostmanUrl;
    description: string;
    body?: {
      mode: 'raw';
      raw: string;
      options: {
        raw: {
          language: 'json';
        };
      };
    };
  };
}

interface PostmanFolderItem {
  name: string;
  item: PostmanRequestItem[];
}

type PostmanItem = PostmanRequestItem | PostmanFolderItem;

export function generatePostmanCollection(
  routes: RouteInfo[],
  frameworkName: string,
  baseUrl: string = 'http://localhost:3000'
): string {
  const requestItems: PostmanRequestItem[] = [];

  for (const route of routes) {
    const postmanPath = toPostmanPath(route.path);
    const pathParts = postmanPath.split('/').filter(Boolean);
    const variables = collectPathVariables(pathParts);
    const query = route.queryParams?.map(param => ({
      key: param.name,
      value: '',
      disabled: !param.required,
    }));
    const queryString = query && query.length > 0
      ? `?${query.map(param => `${param.key}=`).join('&')}`
      : '';

    const url: PostmanUrl = {
      raw: `{{base_url}}${postmanPath}${queryString}`,
      host: ['{{base_url}}'],
    };

    if (pathParts.length > 0) {
      url.path = pathParts;
    }

    if (query && query.length > 0) {
      url.query = query;
    }

    if (variables.length > 0) {
      url.variable = variables.map(v => ({ key: v.key, value: v.value }));
    }

    const headers = buildHeaders(route);
    const request: PostmanRequestItem['request'] = {
      method: route.method,
      header: headers,
      url,
      description: route.description || `${route.method} ${route.path}`,
    };

    if (route.body !== undefined) {
      request.body = {
        mode: 'raw',
        raw: typeof route.body === 'string' ? route.body : JSON.stringify(route.body, null, 2),
        options: {
          raw: {
            language: 'json',
          },
        },
      };
    }

    requestItems.push({
      name: route.name || `${route.method} ${route.path}`,
      request,
    });
  }

  const collection = {
    info: {
      _postman_id: generateId(),
      name: `${frameworkName} API (auto-generated)`,
      description: `Auto-generated by route2postman from ${frameworkName} routes.`,
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    item: groupItemsByResource(requestItems),
    variable: buildCollectionVariables(routes, baseUrl),
  };

  return JSON.stringify(collection, null, 2);
}

function buildHeaders(route: RouteInfo): PostmanHeader[] {
  const headers = { ...(route.headers ?? {}) };

  if (route.body !== undefined && !hasHeader(headers, 'content-type')) {
    headers['Content-Type'] = 'application/json';
  }

  if (route.auth && !hasHeader(headers, 'authorization')) {
    headers.Authorization = 'Bearer {{token}}';
  }

  return Object.entries(headers).map(([key, value]) => ({ key, value }));
}

function buildCollectionVariables(routes: RouteInfo[], baseUrl: string): PostmanVariable[] {
  const variables = new Map<string, PostmanVariable>();
  variables.set('base_url', { key: 'base_url', value: baseUrl, type: 'string' });

  for (const route of routes) {
    if (route.auth) {
      variables.set('token', { key: 'token', value: '', type: 'string' });
    }

    for (const [headerName, headerValue] of Object.entries(route.headers ?? {})) {
      if (headerName.toLowerCase().includes('api-key') || headerValue.includes('{{api_key}}')) {
        variables.set('api_key', { key: 'api_key', value: '', type: 'string' });
      }
    }
  }

  return [...variables.values()];
}

function groupItemsByResource(items: PostmanRequestItem[]): PostmanItem[] {
  const folders = new Map<string, PostmanRequestItem[]>();
  const rootItems: PostmanRequestItem[] = [];

  for (const item of items) {
    const rawPath = item.request.url.path?.[0];
    if (!rawPath) {
      rootItems.push(item);
      continue;
    }

    const folderName = titleCase(rawPath.replace(/^:/, 'params'));
    const folderItems = folders.get(folderName) ?? [];
    folderItems.push(item);
    folders.set(folderName, folderItems);
  }

  return [
    ...rootItems,
    ...[...folders.entries()].map(([name, folderItems]) => ({
      name,
      item: folderItems,
    })),
  ];
}

function toPostmanPath(routePath: string): string {
  const normalizedPath = routePath.startsWith('/') ? routePath : `/${routePath}`;

  return normalizedPath
    .split('/')
    .map(segment => {
      const fastApiParam = segment.match(/^\{([^}:]+)(?::[^}]+)?}$/);
      if (fastApiParam) return `:${fastApiParam[1]}`;

      const djangoParam = segment.match(/^<(?:(?:[^:>]+):)?([^>]+)>$/);
      if (djangoParam) return `:${djangoParam[1]}`;

      return segment;
    })
    .join('/');
}

function collectPathVariables(pathParts: string[]): PostmanVariable[] {
  const variables = new Map<string, PostmanVariable>();

  for (const part of pathParts) {
    if (!part.startsWith(':') || part.length === 1) continue;

    const key = part.slice(1);
    if (!variables.has(key)) variables.set(key, { key, value: '' });
  }

  return [...variables.values()];
}

function hasHeader(headers: Record<string, string>, name: string): boolean {
  return Object.keys(headers).some(key => key.toLowerCase() === name.toLowerCase());
}

function titleCase(value: string): string {
  return value
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, letter => letter.toUpperCase());
}

function generateId(): string {
  const hex = '0123456789abcdef';
  const sections = [8, 4, 4, 4, 12];
  return sections.map(len => {
    let s = '';
    for (let i = 0; i < len; i++) s += hex[Math.floor(Math.random() * 16)];
    return s;
  }).join('-');
}
